(cl:in-package #:clordane)

(clim:define-application-frame clordane ()
  ()
  (:panes (backtrace :application :scroll-bars nil)
          (source :application :scroll-bars nil)
          (repl :application :scroll-bars nil)
          (interactor :interactor :scroll-bars nil))
  (:layouts (default (clim:horizontally (:width 1200 :height 900)
                       (clim:vertically ()
                         (4/5 (clim:scrolling () backtrace))
                         (1/5 (clim:scrolling () interactor)))
                       (clim:vertically ()
                         (4/5 (clim:scrolling () source))
                         (1/5 (clim:scrolling () repl)))))))

(defun clordane ()
  (clim:run-frame-top-level (clim:make-application-frame 'clordane)))

(define-clordane-command (com-quit :name t) ()
  (clim:frame-exit clim:*application-frame*))
